name: stream_video_push_notification_example

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  stream_video: ^1.2.2
  stream_video_push_notification: ^1.2.2

dependency_overrides:
  stream_video:
    path: ../../stream_video
  stream_video_push_notification:
    path: ../../stream_video_push_notification
