name: dogfooding
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_messaging: ^14.2.1
  flutter_svg: ^1.1.6
  google_sign_in: ^5.4.4
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.17
  stream_video:
    path: ../packages/stream_video
  stream_video_flutter:
    path: ../packages/stream_video_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
