name: flutter_dogfooding
version: 1.0.0+1
publish_to: none
description: Flutter Dogfooding App to showcase Video SDK.

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  crypto: ^3.0.3
  cupertino_icons: ^1.0.5
  device_info_plus: ^9.0.3
  envied: ^0.3.0+3
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_messaging: ^14.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  http: ^1.1.0
  path_provider: ^2.1.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  stream_chat_flutter: ^8.0.0-beta.1
  stream_video_flutter: ^0.3.2
  stream_video_push_notification: ^0.3.2
  uni_links: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.1
  import_sorter: ^4.6.0
  pubspec_dependency_sorter: ^1.0.4

import_sorter:
  emojis: true

flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_icons:
  image_path: "assets/ic_launcher.png"

  android: true
  adaptive_icon_background: "assets/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true