name: flutter_dogfooding
version: 1.8.4+1
publish_to: none
description: Flutter Dogfooding App to showcase Video SDK.

environment:
  sdk: ^3.6.2
  flutter: ">=3.27.4"

dependencies:
  app_links: ^6.3.2
  crypto: ^3.0.5
  cupertino_icons: ^1.0.8
  device_info_plus: ">=10.1.2 <12.0.0"
  envied: ^0.5.4+1
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.3.0
  firebase_messaging: ^15.2.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_rating_stars: ^1.1.0
  flutter_svg: ^2.0.7
  get_it: ^7.7.0
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  package_info_plus: ^8.1.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  stream_chat_flutter: ^9.6.0
  stream_video_flutter: ^0.8.4
  stream_video_push_notification: ^0.8.4
  stream_video_screen_sharing: ^0.8.4

dependency_overrides:
  just_audio_web: ^0.4.13
  wakelock_plus: ^1.2.9
  stream_video:
    path: ../packages/stream_video
  stream_video_flutter:
    path: ../packages/stream_video_flutter
  stream_video_push_notification:
    path: ../packages/stream_video_push_notification
  stream_video_screen_sharing:
    path: ../packages/stream_video_screen_sharing

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.5.4+1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.1
  import_sorter: ^4.6.0
  pubspec_dependency_sorter: ^1.0.4

import_sorter:
  emojis: true

flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/ic_launcher.png"

  android: true
  adaptive_icon_background: "assets/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
