name: flutter_dogfooding
description: Flutter Dogfooding App to showcase Video SDK.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  envied: ^0.3.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.4
  http: ^0.13.5
  shared_preferences: ^2.0.17
  stream_video:
    path: ../packages/stream_video
  stream_video_flutter:
    path: ../packages/stream_video_flutter
  stream_video_push_notification:
    path: ../packages/stream_video_push_notification
  uni_links: ^0.5.1

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: "assets/app_icon.png"
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true