name: flutter_dogfooding
description: Flutter Dogfooding App to showcase Video SDK.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  crypto: ^3.0.3
  cupertino_icons: ^1.0.5
  device_info_plus: ^9.0.3
  envied: ^0.3.0+3
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.4
  http: ^0.13.0
  path_provider: ^2.1.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  stream_chat_flutter: ^6.8.1
  stream_video: ^0.0.2
  stream_video_flutter: ^0.0.3
  stream_video_push_notification: ^0.0.3
  uni_links: ^0.5.1

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0+3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: "assets/app_icon.png"
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
