name: flutter_dogfooding
version: 2.2.1+1
publish_to: none
description: Flutter Dogfooding App to showcase Video SDK.

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  app_links: ^6.4.1
  collection: ^1.19.1
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  envied: ^1.2.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1
  firebase_messaging: ^16.0.1
  fl_chart: ^1.1.0
  flutter:
    sdk: flutter
  flutter_rating_stars: ^1.1.0
  flutter_svg: ^2.0.7
  get_it: ^8.2.0
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  google_sign_in: ^7.2.0
  http: ^1.5.0
  mobile_scanner: ^7.1.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  stream_chat_flutter: ^9.17.0
  stream_video_filters: ^1.2.2
  stream_video_flutter: ^1.2.2
  stream_video_noise_cancellation: ^1.2.2
  stream_video_push_notification: ^1.2.2
  stream_video_screen_sharing: ^1.2.2

dependency_overrides:
  stream_video:
    path: ../packages/stream_video
  stream_video_filters:
    path: ../packages/stream_video_filters
  stream_video_flutter:
    path: ../packages/stream_video_flutter
  stream_video_noise_cancellation:
    path: ../packages/stream_video_noise_cancellation
  stream_video_push_notification:
    path: ../packages/stream_video_push_notification
  stream_video_screen_sharing:
    path: ../packages/stream_video_screen_sharing

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^1.2.1
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.0.1
  import_sorter: ^4.6.0
  pubspec_dependency_sorter: ^1.0.4

import_sorter:
  emojis: true

flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/ic_launcher.png"

  android: true
  adaptive_icon_background: "assets/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
