name: example
description: An example project for the stream_video_flutter package.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  cupertino_icons: ^1.0.5
  device_info_plus: ^12.1.0
  envied: ^1.2.1
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.20.0
  path_provider: ^2.1.0
  rxdart: ^0.28.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  stream_video: ^1.2.2
  stream_video_flutter: ^1.2.2
  stream_video_push_notification: ^1.2.2
  stream_webrtc_flutter: ^2.2.3

dependency_overrides:
  stream_video:
    path: ../../stream_video
  stream_video_flutter:
    path: ../../stream_video_flutter
  stream_video_push_notification:
    path: ../../stream_video_push_notification

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^1.2.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
