name: stream_video_dart
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  http: ^0.13.4
  protobuf: ^2.0.1
  tart: ^0.2.0
dev_dependencies:
  lints: ^1.0.0
