name: video_with_chat
description: Video with chat example.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Stream Chat SDK
  stream_chat_flutter:
    git:
      url: https://github.com/GetStream/stream-chat-flutter
      path: packages/stream_chat_flutter

  # Stream Video SDK
  stream_video:
    path: ../../packages/stream_video
  stream_video_flutter:
    path: ../../packages/stream_video_flutter
  envied: ^0.3.0

dependency_overrides:
  rate_limiter: ^1.0.0

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
