name: stream_video
description: The Official Low-level Client for Stream Video, a service for
  building video calls, audio rooms, and live-streaming applications.
version: 1.2.2
homepage: https://getstream.io/video/
repository: https://github.com/GetStream/stream-video-flutter
issue_tracker: https://github.com/GetStream/stream-video-flutter/issues

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  async: ^2.12.0
  battery_plus: ^7.0.0
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  dart_webrtc: ^1.5.3+hotfix.2
  device_info_plus: ^12.1.0
  equatable: ^2.0.7
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  http: ^1.1.0
  internet_connection_checker_plus: ^2.9.0
  intl: ">=0.18.1 <=0.21.0"
  jose: ^0.3.4
  meta: ^1.16.0
  package_info_plus: ^9.0.0
  protobuf: ^5.0.0
  rxdart: ^0.28.0
  sdp_transform: ^0.3.2
  state_notifier: ^1.0.0
  stream_webrtc_flutter: ^2.2.3
  synchronized: ^3.1.0
  system_info2: ^4.0.0
  tart: ^0.6.0
  thermal: ^1.1.11
  uuid: ^4.5.1
  web: ^1.0.0
  web_socket_channel: ^3.0.3
  webrtc_interface: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  mocktail: ^1.0.0
  protoc_plugin: ^23.0.0
  pubspec_parse: ^1.2.1

topics:
  - video
  - audio
  - audioroom
  - webrtc
  - livestream
